[package]
name = "ecs"
version = "0.0.1"
authors = ["Corey Richardson <corey@octayn.net>"]
description = "A high-performance, serializable, parallel-capable entity component system"
license = "BSL-1.0"
